name: Build and deploy Node.js app to Azure Web App - timedata

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install
        run: npm install  # Instala todas las dependencias

      - name: Fix permissions
        run: chmod +x node_modules/.bin/*  # Ajustar permisos para los scripts

      - name: Create build directory
        run: mkdir -p build  # Crea el directorio de build

      - name: npm install, build, and test
        run: |
          npm run build --if-present  # Construir la aplicación
          npm run test --if-present    # Ejecutar las pruebas

      - name: Zip artifact for deployment
        run: zip -r release.zip build/*  # Zip solo el contenido de build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_72FAB696390C4C4C9E698B5FFADE8EF7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_74AA9019E9CC45ABB92F6549B6257CF8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FC810B562F91442BA5BB04DBFD7E294D }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'timedata'
          slot-name: 'Production'
          package: .
